add salary
rknightuk/slashpages pull request #6
Opened 2024-10-08 17:20 UTC by thatmlopsguy

Idea from @jamietanna. ~~Correction: Original idea from @Xe~~

2024-10-08 17:44 UTC, jamietanna reviewed
Thank you 💜

As noted on my salary page I've also got a few other folks doing it

I think @xe predates doing it on their site, but I've noticed a few folks doing it since I've publicised mine which is also cool ☺️

2024-10-09 11:07 UTC, jamietanna requested changes
Oh sorry actually I lie - it looks like mine was first (looking at date of the blogs)

2024-10-09 11:47 UTC, Xe approved these changes

2024-10-09 11:47 UTC, Xe commented on pages/salary.md
> +creator_name: Christine Dodrill
```suggestion
creator_name: Xe Iaso
```

LGTM!

2025-02-02 12:54 UTC, closed without merging